
package ru.technonikol.ws.stocks;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeliveryDateQuery_Out", targetNamespace = "http://tn.ru/po/HYB/DeliveryDate")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeliveryDateQueryOut {


    /**
     * 
     * @param parameters
     * @return
     *     returns ru.technonikol.ws.stocks.SendQueryResponse
     */
    @WebMethod(operationName = "DeliveryDateQuery_Out", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "SendQueryResponse", targetNamespace = "http://tn.ru/po/UTS/DeliveryCost", partName = "parameters")
    public SendQueryResponse deliveryDateQueryOut(
        @WebParam(name = "SendQuery", targetNamespace = "http://tn.ru/po/UTS/DeliveryCost", partName = "parameters")
        SendQuery parameters);

}
