
package ru.technonikol.ws.stocks;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DeliveryDateQuery_OutService", targetNamespace = "http://tn.ru/po/HYB/DeliveryDate", wsdlLocation = "http://dpo.1plt.ru:50000/dir/wsdl?p=ic/e182b89861983bde94df765e028a5802")
public class DeliveryDateQueryOutService
    extends Service
{

    private final static URL DELIVERYDATEQUERYOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException DELIVERYDATEQUERYOUTSERVICE_EXCEPTION;
    private final static QName DELIVERYDATEQUERYOUTSERVICE_QNAME = new QName("http://tn.ru/po/HYB/DeliveryDate", "DeliveryDateQuery_OutService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://dpo.1plt.ru:50000/dir/wsdl?p=ic/e182b89861983bde94df765e028a5802");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DELIVERYDATEQUERYOUTSERVICE_WSDL_LOCATION = url;
        DELIVERYDATEQUERYOUTSERVICE_EXCEPTION = e;
    }

    public DeliveryDateQueryOutService() {
        super(__getWsdlLocation(), DELIVERYDATEQUERYOUTSERVICE_QNAME);
    }

    public DeliveryDateQueryOutService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DELIVERYDATEQUERYOUTSERVICE_QNAME, features);
    }

    public DeliveryDateQueryOutService(URL wsdlLocation) {
        super(wsdlLocation, DELIVERYDATEQUERYOUTSERVICE_QNAME);
    }

    public DeliveryDateQueryOutService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DELIVERYDATEQUERYOUTSERVICE_QNAME, features);
    }

    public DeliveryDateQueryOutService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryDateQueryOutService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryDateQueryOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public DeliveryDateQueryOut getHTTPPort() {
        return super.getPort(new QName("http://tn.ru/po/HYB/DeliveryDate", "HTTP_Port"), DeliveryDateQueryOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryDateQueryOut
     */
    @WebEndpoint(name = "HTTP_Port")
    public DeliveryDateQueryOut getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tn.ru/po/HYB/DeliveryDate", "HTTP_Port"), DeliveryDateQueryOut.class, features);
    }

    /**
     * 
     * @return
     *     returns DeliveryDateQueryOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public DeliveryDateQueryOut getHTTPSPort() {
        return super.getPort(new QName("http://tn.ru/po/HYB/DeliveryDate", "HTTPS_Port"), DeliveryDateQueryOut.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryDateQueryOut
     */
    @WebEndpoint(name = "HTTPS_Port")
    public DeliveryDateQueryOut getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://tn.ru/po/HYB/DeliveryDate", "HTTPS_Port"), DeliveryDateQueryOut.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DELIVERYDATEQUERYOUTSERVICE_EXCEPTION!= null) {
            throw DELIVERYDATEQUERYOUTSERVICE_EXCEPTION;
        }
        return DELIVERYDATEQUERYOUTSERVICE_WSDL_LOCATION;
    }

}
